# Generated by Django 4.2.27 on 2026-02-19 00:00

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0081_alter_device_device_redundancy_group_priority_and_more'),
        ('extras', '0133_alter_approvalworkflowstageresponse_options_and_more'),
        ('ipam', '0054_namespace_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('network', models.CharField(help_text="Route prefix in CIDR notation, e.g. '10.0.0.0/8'", max_length=50)),
                ('prefix_length', models.PositiveSmallIntegerField(help_text='Numeric prefix length (e.g. 8 for /8) — for efficient range queries')),
                ('protocol', models.CharField(choices=[('ospf', 'OSPF'), ('bgp', 'BGP'), ('static', 'Static'), ('connected', 'Connected'), ('isis', 'IS-IS'), ('rip', 'RIP'), ('eigrp', 'EIGRP'), ('local', 'Local'), ('unknown', 'Unknown')], help_text='Routing protocol (normalized to lowercase)', max_length=20)),
                ('next_hop', models.CharField(blank=True, default='', help_text='Next-hop IP address (empty for CONNECTED/LOCAL routes)', max_length=50)),
                ('metric', models.PositiveIntegerField(default=0, help_text='Route metric or cost')),
                ('admin_distance', models.PositiveSmallIntegerField(default=0, help_text="Administrative distance (NAPALM 'preference' field)")),
                ('is_active', models.BooleanField(default=True, help_text='Whether the route is currently installed in the FIB (current_active)')),
                ('routing_table', models.CharField(default='default', help_text="Raw routing table name from device (e.g. 'default', 'inet.0' on JunOS)", max_length=100)),
                ('first_seen', models.DateTimeField(auto_now_add=True, help_text='When this route combination was first detected')),
                ('last_seen', models.DateTimeField(help_text='When this route was last seen (updated on each scan)')),
                ('device', models.ForeignKey(help_text='Device from which the route was collected', on_delete=django.db.models.deletion.CASCADE, related_name='route_entries', to='dcim.device')),
                ('vrf', models.ForeignKey(blank=True, help_text='VRF for this route (null = global routing table)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_entries', to='ipam.vrf')),
                ('outgoing_interface', models.ForeignKey(blank=True, help_text='Outgoing interface (optional, mainly for CONNECTED/LOCAL routes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_entries', to='dcim.interface')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Route Entry',
                'verbose_name_plural': 'Route Entries',
                'ordering': ['-last_seen'],
                'indexes': [
                    models.Index(fields=['device', 'last_seen'], name='idx_route_device_lastseen'),
                    models.Index(fields=['network', 'last_seen'], name='idx_route_network_lastseen'),
                    models.Index(fields=['protocol', 'last_seen'], name='idx_route_protocol_lastseen'),
                    models.Index(fields=['last_seen'], name='idx_route_lastseen'),
                    models.Index(fields=['first_seen'], name='idx_route_firstseen'),
                ],
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='routeentry',
            constraint=models.UniqueConstraint(fields=('device', 'vrf', 'network', 'next_hop', 'protocol'), name='nautobot_route_tracking_routeentry_unique_route'),
        ),
    ]
