# Generated by Django 4.2.28 on 2026-02-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_route_tracking', '0002_add_partial_unique_constraint_no_vrf'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='routeentry',
            index=models.Index(fields=['vrf', 'last_seen'], name='idx_route_vrf_lastseen'),
        ),
    ]
